version: '3.8'
services:
  postgres:
    image: postgres:13.0
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./pg-data/postgres:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 18080:8080
